name: TestApp & Deploy

on:
  push:
    branches:
      - master
      - main
      - dev

jobs:

## CREATE ENV ##

  CreateEnvFile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/Checkout@v2
      - name: Create .env file
        run: |
          touch .env
          echo ${{ secrets.ENV }} | base64 -d > .env

## TEST APP ##

  AppTest:
    needs:
      - CreateEnvFile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/Checkout@v2

      - name: Install and set flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'

      - name: Upgrade flutter
        run: flutter upgrade

      - name: Check flutter
        run: flutter doctor

      - name: Create .env file
        run: |
          touch .env
          echo ${{ secrets.ENV }} | base64 -d > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Check norme
        run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Test Build
        run: flutter build apk --debug

## DOCKER ##

  DockerTest:
    needs:
      - AppTest
    runs-on: ubuntu-latest

    steps:

      - uses: actions/Checkout@v2

      - name: Create .env file
        run: |
          touch .env
          echo ${{ secrets.ENV }} | base64 -d > .env

      - name: Compile app
        shell: bash
        run: docker build ./

## DEPLOYEMENT ##

  Deployement:
    needs:
      - CreateEnvFile
      - AppTest
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - uses: actions/Checkout@v2

      - name: Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree ./ add --all
          git commit -m "Deployment"
          git push origin HEAD:deploy --force

      - name: Deployement
        run: |
          echo "Push successfuly"
          echo "Deployement is starting"
