name: CreateEnvFile

on:
  workflow_call:

jobs:
  CreateEnvFile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          touch .env
          echo TYPE=${{ secrets.TYPE }} | base64 >> .env
          echo PROJECT_ID=${{ secrets.PROJECT_ID }} | base64 >> .env
          echo PRIVATE_KEY_ID=${{ secrets.PRIVATE_KEY_ID }} | base64 >> .env
          echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} | base64 >> .env
          echo CLIENT_EMAIL=${{ secrets.CLIENT_EMAIL }} | base64 >> .env
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} | base64 >> .env
          echo AUTH_URI=${{ secrets.AUTH_URI }} | base64 >> .env
          echo TOKEN_URI=${{ secrets.TOKEN_URI }} | base64 >> .env
          echo AUTH_PROVIDER_X509_CERT_URL=${{ secrets.AUTH_PROVIDER_X509_CERT_URL }} | base64 >> .env
          echo CLIENT_X509_CERT_URL=${{ secrets.CLIENT_X509_CERT_URL }} | base64 >> .env
          echo SPREADSHEET_ID=${{ secrets.SPREADSHEETID }} | base64 >> .env
          echo TITLE_FAQ=${{ secrets.TITLE_FAQ }} | base64 >> .env